[project]
name = "riverborn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "glfw>=2.8.0",
    "pygfx>=0.9.0",
]

[project.scripts]
riverborn = "riverborn:main"


[build-system]
requires = ["flit_scm>=1.7.0"]
build-backend = "flit_scm:buildapi"

[tool.flit.sdist]
exclude = [".gitignore"]

[tool.setuptools_scm]
write_to = "src/riverborn/_version.py"
relative_to = "pyproject.toml"
